### ISSUE TITLE
Feature request: graceful shutdown

### ISSUE THREAD

**Issue by igrep** [iij-ii/direct-hs#15]
According to developers of LisB and a bot provider I talked with, we should add some feature to resume a channel (conversation with a user) after bot restarts during the conversation.
They said that with bots with a huge number of users, someone often accidentally stops their conversations due to some reasons.
Without resume feature, the state of conversations gets lost when the bot shuts down or crash.

**Comment by kazu-yamamoto** [comment]
Resume is important for Direct JS since Hubot is rebooted repeatedly.
However, Direct HS is not rebooted repeatedly and will be rebooted at maintenance time
For Direct HS, it is important to prepare graceful shutdown feature.
So, let's prepare an API to signal all existing worker threads to send a maintenance message to their user.
